"""
Day 12 - Aug 17

You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘. 
Note: You may assume that at most one additional character can be added to t. 

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''

"""

s = input()
t = input()

def extraChar(s, t):
  hash = {}
  for letter in s:
    if letter in hash:
      hash[letter] += 1
    else:
      hash[letter] = 1
      
  for letter in t:
    if letter in hash and hash[letter] > 0:
      hash[letter] -= 1
    else:
      return letter

  return ''

"""
Time Complexity: O(n) where n = max(len(s), len(t))
"""

print(extraChar(s, t))
